name: CI/CD Pipeline
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
      display-name: 'Set up Python 3.12'
    - name: Install Poetry
      run: |
        pip install poetry
      display-name: 'Install Poetry'
    - name: Install dependencies
      run: |
        poetry install
    - name: Run tests
      run: |
        poetry run pytest
    - name: Build Docker image
      run: |
        docker build -t mlops-demo .
    - name: Test Docker container
      run: |
        docker run -d -p 80:80 --name mlops-demo mlops-demo
        sleep 5
        curl -X POST http://localhost/predict -H "Content-Type: application/json" -d '{"data": [5.1, 3.5, 1.4, 0.2]}'
    - name: Build and Release Package
      if: github.ref == 'refs/heads/main'
      run: |
        poetry build
        gh release create v0.1.0 dist/* --title "v0.1.0" --notes "Initial release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}